name: flutter_kakao_login
description: A Flutter plugin for using the native Kakao Login SDKs on Android and iOS
version: 3.4.0
homepage: https://github.com/JosephNK/flutter_kakao_login

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.josephnk.flutter_kakao_login
        pluginClass: FlutterKakaoLoginPlugin
      ios:
        pluginClass: FlutterKakaoLoginPlugin
